#ifndef MYDRIVER_IOCTLS
#define MYDRIVER_IOCTLS

#define MYDRIVER_CMD1 0
#define MYDRIVER_CMD2 1
#define MYDRIVER_CMD3 2

#define MYDRIVER_IOCTL_BASE 'Ö'
#define MYDRIVER_IOCTL_CMD1 _IO(MYDRIVER_IOCTL_BASE, MYDRIVER_CMD1)
#define MYDRIVER_IOCTL_CMD2 _IO(MYDRIVER_IOCTL_BASE, MYDRIVER_CMD2)
#define MYDRIVER_IOCTL_CMD3 _IO(MYDRIVER_IOCTL_BASE, MYDRIVER_CMD3)

#endif
